@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(administrator, "Administrator")
Person(patient, "Patient")

System_Boundary(logSystem, "Система хранения логов доступа к данным") {
    Container(logService, "Log Service", "Java", "Сохраняет логи доступа и выгружает их")
    ContainerDb(logServiceDB, "БД", "Postgres", "Хранит логи")

    Rel(logService, logServiceDB, "Сохрание логов")
}

System_Boundary(iamSystem, "IAM") {
    Container(iamServiceAuthentication, "Authentication", "Java", "Сервис по проверке аутентификации пользователей")
    Container(iamServiceAuthorization, "Authorization", "Java", "Сервис по проверке авторизации пользователей")
    ContainerDb(iamServiceDB, "БД", "Postgres", "Хранит связи атрибутов с данными и данные пользователей")

    Rel(iamServiceAuthentication, iamServiceDB, "Сохрание данных")
    Rel(iamServiceAuthorization, iamServiceDB, "Сохрание данных")
}

note bottom of iamServiceAuthorization
На основе атрибутов полльзователя (ABAC) проверяет доступ к данным по тегам:
- персональной информации пациента
- мед книжки
- данных анализов
- расписания
- файлам

Администратор имеет доступ к тегам "PII" когда имеет атрибут "работает", который проставляется во время его работы

Пациент имеет доступ к тегам "PII", "PHI", "Клинические данные", которые связаны с ним по его идентификатору
end note

System_Boundary(patientSystem, "Система по хранению данных пользователей") {
    Container(patientService, "Patient", "Java", "Сервис отвечающий за доступ к персональным данным пользователей")
    ContainerDb(patientPIIDB, "Patient PII БД", "Postgres", "Хранит PII данные пользователей")
    ContainerDb(patientDB, "Patient БД", "Postgres", "Хранит PHI и клинические данные пользователей")
    Container(patientS3, "S3", "S3")

    Rel(patientService, patientS3, "Сохрание файлов пациентов")
    Rel(patientService, patientPIIDB, "Сохрание PII данных о пациенте")
    Rel(patientService, patientDB, "Сохрание данных о пациенте")
}

note bottom of patientPIIDB
Хранит персональную информацию о пользователях
- ФИО, дату рождения, телефон и электронную почту: имеет тег "PII"
- дополнительную информацию: имеет тег "PII"

Все данные в этой БД имеет тег "PII".

БД шифрует свои данные
end note

note bottom of patientDB
Хранит остальную информацию о пользователях
- результаты анализов: имеет тег "Клинические данные"
- связи с файлами

Данные размечаются тегами автоматически в зависимости нахождения в определенной таблице

БД шифрует свои данные
end note

note bottom of patientS3
Хранит файлы пользователей (снимки, результаты анализов и прочее): имеет тег "Клинические данные"

Шифрует свои данные
end note

System_Boundary(journalSystem, "Система по хранению расписаний") {
    Container(journalService, "Journals", "Java", "Сервис отвечающий за доступ к расписаниям врачей")
    ContainerDb(journalDB, "Journal БД", "Postgres")

    Rel(journalService, journalDB, "Сохрание данных о записях к врачу")
}

note bottom of journalDB
Хранит пациентов записи к врачам:
- ид пациета, врач, время: имеет тег "Запись к врачу"

Данные размечаются тегами автоматически в зависимости нахождения в определенной таблице

БД шифрует свои данные
end note

System_Boundary(clientPortal, "Портал для клиентов") {
    Container(clientPortalFront, "Front", "React", "Сайт")
    Container(clientPortalBack, "Back", "Java")

    Rel(clientPortalFront, clientPortalBack, "Использование API")
}

System_Boundary(administratorPortal, "Портал для сотрудников ресепшена") {
    Container(administratorPortalFront, "Front", "React", "Сайт")
    Container(administratorPortalBack, "Back", "Java")

    Rel(administratorPortalFront, administratorPortalBack, "Использование API")
}

Rel(clientPortalBack, journalService, "Сохранение записи о враче", "HTTPS")
Rel(clientPortalBack, patientService, "Просмотр и изменение информации о пациенте", "HTTPS")
Rel(clientPortalBack, iamServiceAuthentication, "Проверка пациента на доступа к ресурсам", "HTTPS")

Rel(administratorPortalBack, patientService, "Сохранение информации о пациенте", "HTTPS")
Rel(administratorPortalBack, journalService, "Просмотр информации о записи к врачу", "HTTPS")
Rel(administratorPortalBack, iamServiceAuthentication, "Проверка администратора на доступа к ресурсам", "HTTPS")

Rel(patient, clientPortalFront, "Запись к врачу / Изменение своих данных / Просмотр файлов", "HTTPS")

Rel(administrator, administratorPortalFront, "Просмотр / Регистрация пользователя", "HTTPS")

Rel(patientService, iamServiceAuthorization, "Проверка доступов к данным", "HTTPS")
Rel(journalService, iamServiceAuthorization, "Проверка доступов к данным", "HTTPS")

Rel(patientService, logService, "Сохранение информации о запросе данных", "HTTPS")
Rel(journalService, logService, "Сохранение информации о запросе данных", "HTTPS")

@enduml
